// @ts-nocheck

export const iconPaths = {
  bell: () => import('./icons/zhique_ui/bell.svg'),
  github: () => import('./icons/zhique_ui/github.svg'),
  arrowLeft: () => import('./icons/zhique_ui/arrowLeft.svg'),
  arrowDown: () => import('./icons/zhique_ui/arrowDown.svg'),
  arrowRight: () => import('./icons/zhique_ui/arrowRight.svg'),
  menu_open: () => import('./icons/zhique_ui/menu_open.svg'),
  plus: () => import('./icons/zhique_ui/plus.svg'),
  empty_1: () => import('./icons/zhique_ui/empty_1.svg'),
  'zhique_ui/wechat': () => import('./icons/zhique_ui/wechat.svg'),
  'zhique_ui/github': () => import('./icons/zhique_ui/github.svg'),

  'menu/team_app': () => import('./icons/zhique_ui/menu/team_app.svg'),
  'menu/home': () => import('./icons/zhique_ui/menu/home.svg'),
  'menu/star': () => import('./icons/zhique_ui/menu/star.svg'),
  'menu/home_active': () => import('./icons/zhique_ui/menu/home_active.svg'),
  'menu/team_app_active': () => import('./icons/zhique_ui/menu/team_app_active.svg'),
  'menu/agent': () => import('./icons/zhique_ui/menu/agent.svg'),
  'menu/utils': () => import('./icons/zhique_ui/menu/utils.svg'),
  'menu/sys_utils': () => import('./icons/zhique_ui/menu/sys_utils.svg'),
  'menu/market': () => import('./icons/zhique_ui/menu/market.svg'),
  'menu/MCP': () => import('./icons/zhique_ui/menu/MCP.svg'),
  'menu/agent_test': () => import('./icons/zhique_ui/menu/agent_test.svg'),
  'menu/star_active': () => import('./icons/zhique_ui/menu/star_active.svg'),
  'menu/personal_info': () => import('./icons/zhique_ui/menu/personal_info.svg'),
  'menu/personal_info_active': () => import('./icons/zhique_ui/menu/personal_info_active.svg'),
  'menu/api_keys': () => import('./icons/zhique_ui/menu/api_keys.svg'),
  'menu/billing': () => import('./icons/zhique_ui/menu/billing.svg'),
  'menu/connected_accounts': () => import('./icons/zhique_ui/menu/connected_accounts.svg'),
  'menu/custom_domain': () => import('./icons/zhique_ui/menu/custom_domain.svg'),
  'menu/locale_settings': () => import('./icons/zhique_ui/menu/locale_settings.svg'),
  'menu/logout': () => import('./icons/zhique_ui/menu/logout.svg'),
  'menu/model_providers': () => import('./icons/zhique_ui/menu/model_providers.svg'),
  'menu/notifications': () => import('./icons/zhique_ui/menu/notifications.svg'),
  'menu/plan_usage': () => import('./icons/zhique_ui/menu/plan_usage.svg'),
  'menu/portal_config': () => import('./icons/zhique_ui/menu/portal_config.svg'),
  'menu/team_mgmt': () => import('./icons/zhique_ui/menu/team_mgmt.svg'),
  'menu/activity_log': () => import('./icons/zhique_ui/menu/activity_log.svg'),
  'menu/knowledge_base_count': () => import('./icons/zhique_ui/menu/knowledge_base_count.svg'),
  'menu/knowledge_base': () => import('./icons/zhique_ui/menu/knowledge_base.svg'),

  'chat/send': () => import('./icons/zhique_ui/chat/send.svg'),
  'chat/microphone': () => import('./icons/zhique_ui/chat/microphone.svg'),
  'chat/paper_clip': () => import('./icons/zhique_ui/chat/paper_clip.svg'),
  'chat/message': () => import('./icons/zhique_ui/chat/message.svg'),
  'chat/export_md': () => import('./icons/zhique_ui/chat/export_md.svg'),
  'chat/copy': () => import('./icons/zhique_ui/chat/copy.svg'),
  'chat/read': () => import('./icons/zhique_ui/chat/read.svg'),
  'chat/thumbs_down': () => import('./icons/zhique_ui/chat/thumbs_down.svg'),
  'chat/thumbs_up': () => import('./icons/zhique_ui/chat/thumbs_up.svg'),
  'chat/messageItem': () => import('./icons/zhique_ui/chat/messageItem.svg'),
  'chat/messageItem_active': () => import('./icons/zhique_ui/chat/messageItem_active.svg'),
  'chat/more_small': () => import('./icons/zhique_ui/chat/more_small.svg'),
  'chat/edit_pen': () => import('./icons/zhique_ui/chat/edit_pen.svg'),
  'chat/cancel_top': () => import('./icons/zhique_ui/chat/cancel_top.svg'),

  'dashboard/import_json': () => import('./icons/zhique_ui/dashboard/import_json.svg'),
  'dashboard/lock': () => import('./icons/zhique_ui/dashboard/lock.svg'),
  'dashboard/dingding': () => import('./icons/zhique_ui/dashboard/dingding.svg'),
  'dashboard/api_request': () => import('./icons/zhique_ui/dashboard/api_request.svg'),
  'dashboard/ignore_login': () => import('./icons/zhique_ui/dashboard/ignore_login.svg'),
  'dashboard/field_config': () => import('./icons/zhique_ui/dashboard/field_config.svg'),
  'dashboard/ai_pref': () => import('./icons/zhique_ui/dashboard/ai_pref.svg'),
  'dashboard/link_lib': () => import('./icons/zhique_ui/dashboard/link_lib.svg'),
  'dashboard/tip_fill': () => import('./icons/zhique_ui/dashboard/tip_fill.svg'),
  'dashboard/checkCircleFill': () => import('./icons/zhique_ui/dashboard/checkCircleFill.svg'),
  'dashboard/import': () => import('./icons/zhique_ui/dashboard/import.svg'),
  'dashboard/folder': () => import('./icons/zhique_ui/dashboard/folder.svg'),

  'dashboard/widget/checkbox': () => import('./icons/zhique_ui/dashboard/widget/checkbox.svg'),
  'dashboard/widget/externalVar': () =>
    import('./icons/zhique_ui/dashboard/widget/externalVar.svg'),
  'dashboard/widget/fileUpload': () => import('./icons/zhique_ui/dashboard/widget/fileUpload.svg'),
  'dashboard/widget/internalVar': () =>
    import('./icons/zhique_ui/dashboard/widget/internalVar.svg'),
  'dashboard/widget/modelSelect': () =>
    import('./icons/zhique_ui/dashboard/widget/modelSelect.svg'),
  'dashboard/widget/numberInput': () =>
    import('./icons/zhique_ui/dashboard/widget/numberInput.svg'),
  'dashboard/widget/radio': () => import('./icons/zhique_ui/dashboard/widget/radio.svg'),
  'dashboard/widget/switch': () => import('./icons/zhique_ui/dashboard/widget/switch.svg'),
  'dashboard/widget/textInput': () => import('./icons/zhique_ui/dashboard/widget/textInput.svg'),
  'dashboard/widget/timePoint': () => import('./icons/zhique_ui/dashboard/widget/timePoint.svg'),
  'dashboard/widget/timeRange': () => import('./icons/zhique_ui/dashboard/widget/timeRange.svg'),
  'dashboard/widget/password': () => import('./icons/zhique_ui/dashboard/widget/password.svg'),

  'account/account': () => import('./icons/zhique_ui/account/account.svg'),
  'account/password': () => import('./icons/zhique_ui/account/password.svg'),
  'account/send': () => import('./icons/zhique_ui/account/send.svg'),
  'account/warning_fill': () => import('./icons/zhique_ui/account/warning_fill.svg'),
  'account/team_info': () => import('./icons/zhique_ui/account/team_info.svg'),
  'account/filter': () => import('./icons/zhique_ui/account/filter.svg'),
  'account/empty_icon': () => import('./icons/zhique_ui/empty_icon.svg'),
  'account/coupon': () => import('./icons/zhique_ui/account/coupon.svg')
};
